google_project_id       = "mineral-order-315523"
google_bucket_name      = "nasyikat-fuchicorp"
deployment_environment  = "qa"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"